### ISSUE TITLE
글쓰기 기본 "테이블"의 "표 테마" 변경시 다크모드에서 폰트색상 반전이 정상동작하지 않는 경우 발생

### ISSUE THREAD

**Issue by progrunman** [tistory-projects/tistory-skin-hELLO#108]
**환경**
- 운영체제: Windows10
- 브라우저: chrome 
- 버전: 102.0.5005.115(공식 빌드) (64비트)
- 스킨 버전: 3.6.1

**설명**
글쓰기에서 삽입된 티스토리 기본 테이블에 특정 테마가 적용되었을시 폰트색상 반전은 배경색에 따라 다르게 동작해야하나 일괄적으로 변경되어 가독성이 떨어지는 경우 발생

**발생 과정**
테마 변경 버튼을 통해 다크 모드로 변경시 테이블에 적용된 폰트반전이 동작하지 않아야할 테마에서도 동작

**스크린샷 및 링크**
![캡처_white](https://user-images.githubusercontent.com/50584589/174014655-21da57ec-28f5-40f0-ad53-6a9077d9fe23.JPG)
![캡처_black](https://user-images.githubusercontent.com/50584589/174014671-91f0609a-f789-487b-af1c-29f3fba02ab3.JPG)

**Comment by pronist** [comment]
@progrunman 이 부분은 신경 못 썼던 부분이군요. 감사합니다.

**Comment by pronist** [comment]
@progrunman 4.0.0 에서 표 테마가 일원화되었습니다. 티스토리에서 제공하는 표 테마의 경우에는 스킨과의 디자인상 조화가 맞지 않아 일원화하기로 하였습니다.
