### ISSUE TITLE
수정, 삭제 버튼이 안보입니다.

### ISSUE THREAD

**Issue by Junhyung-Choi** [tistory-projects/tistory-skin-hELLO#128]
- 운영체제: Window 10 / MacOS Monteray
- 브라우저: Chrome
- 버전: 104.0.5112.102(공식 빌드) (64비트)
- 스킨 버전 (스킨 버전은 index.xml 에서 확인): 3.6.2

글 하단부에서 수정, 혹은 삭제를 모아두는 popover 버튼을 클릭시 수정, 삭제 등의 아이콘이 보이지 않습니다.
화이트. 다크 모드에서도 동일하게 보이지 않습니다.

포스트 주소 : https://theoldface-dev.tistory.com/29
스크린샷
![image](https://user-images.githubusercontent.com/50592308/186680620-970fb108-e5bf-4a02-93c1-f3cb1f0353de.png)

**Comment by pronist** [comment]
@Junhyung-Choi 티스토리가 또 잠수함 패치를 했군요. 그래서 스킨에도 영향이 간 모양입니다. 조만간 패치를 해야겠습니다. 버그신고 감사드립니다.

**Comment by giibeom** [comment]
추가적으로 동일한 스킨에서 상대방의 블로그에 들어갈 경우에도 더보기란(...)에 아이콘 또한 제대로 표출되지 않습니다.
참고 부탁드립니다.

[스크린샷]
![image](https://user-images.githubusercontent.com/59248326/186910644-ea57e8ed-0d3e-454d-b365-7a7db4e7e230.png)

**Comment by pronist** [comment]
@giibeom 감사합니다. 이 문제는 다음 패치 때 수정하도록 하겠습니다 :))
