### ISSUE TITLE
10월 31일 포스팅 글부터 목록에서  대표 이미지가 정말 작게 나옵니다.

### ISSUE THREAD

**Issue by pronist** [tistory-projects/tistory-skin-hELLO#143]
### Discussed in https://github.com/tistory-projects/tistory-skin-hELLO/discussions/142

<div type='discussions-op-text'>

<sup>Originally posted by **Ryan-Dia** November  2, 2022</sup>
운영체제: macOS Monterey
브라우저: chrome
버전:107.0.5304.87(공식 빌드) (arm64)
스킨 버전: 3.6.3

설명
이전글을 그대로인데 10월30일부터 쓴 글부터 저렇게 됩니다. 
갑자기 'element.style'  css가 적용되서 그런 것 같습니다.
이건 티스토리에서 패치해서 그런건가요 ? 
10월 31일 전에는 element.style가 적용이 되어있지 않습니다.
이전 글은 기본에 사진이 없던 글이나 사진이 이미 있어도 교체를 해도 잘되지만 10월 30일 이후 글은 저렇게 작게나옵니다. 

발생 과정
이미지가 아주아주 작게 나옵니다. 

스크린샷 및 링크

블로그 링크 : https://html-jc.tistory.com/?page=1

<img width="1164" alt="image" src="https://user-images.githubusercontent.com/76567238/199298049-bf5cca61-5b4a-4034-8eef-9ba6f9263739.png">

<img width="665" alt="image" src="https://user-images.githubusercontent.com/76567238/199298284-bac28612-ecac-482a-8e2a-c40a68ed6643.png">

기본 상태

<img width="1034" alt="image" src="https://user-images.githubusercontent.com/76567238/199299781-702c6aa3-dd56-47e6-a6f9-01fbabad4cfd.png">

element.style 전부 적용 해제

<img width="978" alt="image" src="https://user-images.githubusercontent.com/76567238/199298459-3c218339-c99a-453b-9290-7d544605697a.png">

</div>

**Comment by jminie-o8o** [comment]
빠른 수정 감사합니다!!

**Comment by Jooooooooooooooooo** [comment]
감사합니다!!!
