### ISSUE TITLE
블로그 홈에서 대표 이미지가 보이지 않는 것 같습니다.

### ISSUE THREAD

**Issue by wlxo0401** [tistory-projects/tistory-skin-hELLO#144]
**환경 (버그가 발생한 환경을 적어주세요.):**

- 운영체제: mac 몬트레이
- 브라우저: Edge
- 버전:  107.0.1418.24 
- 스킨 버전 : 3.6.3

**설명**
https://jiwift.tistory.com/ 메인으로 들어가면 글 목록이 나오는데 카테고리, 제목, 내용요약 순서로 게시글들이 보이는 중에 카테고리 위에 이상한 기호가 같이 출력됨

**발생 과정**
글을 작성하고 메인화면으로 이동해서 글 리스트가 나오는 중에 발생한 버그 
추측으로는 사진이 나와야하는 자리에 사진이 나오지 못하는 것으로 판단.

**스크린샷 및 링크**
버그가 발생한 상황을 가능하다면 스크린샷을 첨부해주세요. 또한 버그가 발생한 모습이 있는 포스트의 주소를 첨부해주시는 것도 아주 좋습니다!
<img width="1728" alt="스크린샷 2022-11-03 오후 10 13 35" src="https://user-images.githubusercontent.com/57979066/199730027-db7038f2-6e1d-4716-9e53-990992b3d2d2.png">

**Comment by pronist** [comment]
@wlxo0401 안녕하세요. 이 문제는 `3.6.4` 버전에서 해결되었습니다.  #142 를 참고해주세요.
