### ISSUE TITLE
신규 작성 게시글 썸네일 이미지 미출력

### ISSUE THREAD

**Issue by kycasdzxc** [tistory-projects/tistory-skin-hELLO#145]
**환경 (버그가 발생한 환경을 적어주세요.):**

- 운영체제: windows
- 브라우저: chrome
- 스킨 버전 (스킨 버전은 index.xml 에서 확인): [e.g 3.4.0] 3.6.3

**설명**
안녕하세요! 퀄리티 높은 스킨을 무료로 제공해주셔서 항상 감사히 쓰고 있습니다.
지난 주에 작성한 게시글부터 게시글 목록에서의 썸네일이 이미지 대신 -"> 가 나옵니다.

![image](https://user-images.githubusercontent.com/105793579/200117682-337b22d5-b996-482a-98ae-6c82f00747af.png)
* 위에 이미지처럼 ""> " 가 추가되어서 그런 게 아닌가 싶습니다.

**스크린샷 및 링크**
저만의 문제인가 싶어서 hELLO 스킨을 사용하는 다른 분들 블로그를 확인해보니 똑같이 발생하였습니다.
<hr>

https://yermi.tistory.com/
![image](https://user-images.githubusercontent.com/105793579/200117562-403061f7-153b-4b53-aebd-cd5e297b2c7d.png)
<hr>

https://dys-r.tistory.com/
![image](https://user-images.githubusercontent.com/105793579/200117597-0d7572e7-895e-4b77-8d9e-c14e3ab33a97.png)

버그가 발생한 상황을 가능하다면 스크린샷을 첨부해주세요. 또한 버그가 발생한 모습이 있는 포스트의 주소를 첨부해주시는 것도 아주 좋습니다!

**Comment by pronist** [comment]
@kycasdzxc 안녕하세요. 이 문제는 `3.6.4` 버전에서 해결이 된 바 있습니다. #142 를 참고해주세요.

**Comment by kycasdzxc** [comment]
@pronist 확인하였습니다, 감사합니다!
