### ISSUE TITLE
게시글 내 이미지 팝업이 되지 않습니다

### ISSUE THREAD

**Issue by kycasdzxc** [tistory-projects/tistory-skin-hELLO#146]
**환경 (버그가 발생한 환경을 적어주세요.):**

- 운영체제: windows
- 브라우저: chrome
- 스킨 버전 (스킨 버전은 index.xml 에서 확인): 3.6.3

**설명**
이전 등록한 issue에 대해 빠른 답변 주셔서 감사합니다.
블로그 게시글 게시 후, 게시된 이미지 클릭 시 팝업이 적용이 되지 않습니다.
(그런데 상우님이 블로그에 올려주신 게시글들은 이미지 팝업이 뜹니다!)

**발생 과정**
버그가 어떤 과정을 통해 발생하는지 구체적으로 적어주세요.
[e.g. 테마 변경 버튼을 통해 화이트 모드로 변경시 코드 하이라이팅의 색상이 변하지 않습니다. ...]

**스크린샷 및 링크**

https://yermi.tistory.com/723

![image](https://user-images.githubusercontent.com/105793579/200118889-ad3a80e2-3955-4fad-b02b-71ab012f3b5d.png)
<hr>

- 팝업이 뜨지 않는 다른 블로그들<br>
https://jiwift.tistory.com/12<br>
https://html-jc.tistory.com/511<br>
https://theoldface-dev.tistory.com/29<br>

<hr>

- 팝업이 뜨는 블로그<br>
https://pronist.dev/5<br>

![image](https://user-images.githubusercontent.com/105793579/200119113-8271a693-d73e-42c5-8879-7700cdac36af.png)

- 좋은 스킨을 제공해주셔서 항상 감사합니다! 🥇 

버그가 발생한 상황을 가능하다면 스크린샷을 첨부해주세요. 또한 버그가 발생한 모습이 있는 포스트의 주소를 첨부해주시는 것도 아주 좋습니다!

**Comment by pronist** [comment]
@kycasdzxc

이 기능은 제 스킨에서 제공하는 고유 기능이 아닙니다. 
티스토리에서 제공했던 라이트박스라는 기능인데, 카카오 티스토리 내부의 문제입니다~
