### ISSUE TITLE
사이드바 방문자수 0명 버그

### ISSUE THREAD

**Issue by jminie-o8o** [tistory-projects/tistory-skin-hELLO#147]
**환경 (버그가 발생한 환경을 적어주세요.):**

- 운영체제: macOS Momentary
- 브라우저: chrome
- 버전: 107.0.5304.87
- 스킨 버전 (스킨 버전은 index.xml 에서 확인): 3.6.4

**설명**
사이드바의 방문자 수가 모두 0명으로 표기됩니다.

**발생 과정**
말 그대로 사이드바 방문자수가 모두 0명으로 표기됩니다. 특이한 건 사이드바 설정에서 미리보기로 보았을 때는 정상적으로 보이는데 설정을 완료하고 
페이지로 돌아오면 모두 0 0 0 으로 표기됩니다.

**스크린샷 및 링크**
![image](https://user-images.githubusercontent.com/79504043/200334972-3d02b70e-e13d-46f9-a6b5-89abde18fd4c.png)

**Comment by pronist** [comment]
@jminie-o8o 안녕하세요~

제가 코멘트를 쓰고 있는 도중에 답글을 달아주셨군요. 

현재 티스토리 내의 애드센스가 출력이 안 된다거나 방문자수가 카운팅이 안 된다거나 하는 등의 버그가 많아서 그런 듯 싶습니다. 특히나 문의주신 방문자 카운팅은 스킨 개발자가 건드릴 수 있는 부분이 없어서 말이죠.

아무튼, 해결되셨다니 다행입니다.
