### ISSUE TITLE
메인으로 사용하는 크롬브라우저에서만 무한로딩이 발생합니다.

### ISSUE THREAD

**Issue by yongwoo-jeong** [tistory-projects/tistory-skin-hELLO#163]
**환경 (버그가 발생한 환경을 적어주세요.):**

- 운영체제:  맥OS 몬테레이 12.6
- 브라우저:  크롬 
- 버전: 108.0.5359.124(공식 빌드) (arm64)
- 스킨 버전 (스킨 버전은 index.xml 에서 확인):  3.6.5

**설명**
버그가 어떻게 발생하는지 알려주세요. 대략적인 버그의 설명을 적어주시면 됩니다.

메인으로 사용하는 크롬브라우저에서만 무한로딩이 발생합니다.
크롬 시크릿모드, 사파리에서는 정상 로딩됩니다.

**발생 과정**
버그가 어떤 과정을 통해 발생하는지 구체적으로 적어주세요.

크롬브라우저 블로그 url  접속시 무한로딩+화면 클릭이 불가능합니다.
화면 사이즈가 고정되는걸로 보아 자바스크립트에서 너비, 높이를 받아오는 과정에 문제가 있는것도 같습니다.
캐시문제인가 싶어 쿠키를 비롯해 기록을 모두 지워봐도 무한로딩이 발생합니다.
스킨 등록시 /image 폴더 안 파일 4개 모두 넣어주었음에도 해당 증생이 발생합니다..
로컬 환경 문제인것같긴한데 혹여나 이런 증상이 있으신분이 계실까싶어 남겨봅니다.

**스크린샷 및 링크**
버그가 발생한 상황을 가능하다면 스크린샷을 첨부해주세요. 또한 버그가 발생한 모습이 있는 포스트의 주소를 첨부해주시는 것도 아주 좋습니다!

**Comment by velpegor** [comment]
저도 같은 현상이 발생합니다.

**Comment by pronist** [comment]
@yongwoo-jeong 혹시 블로그 주소를 알 수 있을까요? 일단, 제 블로그에서는 크롬이나 엣지같은 동일 엔진을 사용한 브라우저로 접속해도 멀쩡하게 나오고 있습니다. 이 문제는 애드블럭(#157)과 같은 플러그인과 충돌해서 발생하는 일도 있었으니 참고해보시는 것이 좋을 것 같습니다.

**Comment by yongwoo-jeong** [comment]
> @yongwoo-jeong 혹시 블로그 주소를 알 수 있을까요? 일단, 제 블로그에서는 크롬이나 엣지같은 동일 엔진을 사용한 브라우저로 접속해도 멀쩡하게 나오고 있습니다. 이 문제는 애드블럭(#157)과 같은 플러그인과 충돌해서 발생하는 일도 있었으니 참고해보시는 것이 좋을 것 같습니다.

동일한 애드블럭 플러그인 사용중이었고 문제화면에서 콘솔을 확인하니 동일한 증상인듯 합니다.
**애드블럭에서 제 블로그 주소를 예외처리하니 정상 접속이 가능합니다.**
왜 동일 증상임을 인지하지못했을까요?
도움주셔서 감사합니다.
