### ISSUE TITLE
이미지링크가 깨집니다.

### ISSUE THREAD

**Issue by KimJason8557** [tistory-projects/tistory-skin-hELLO#168]
**환경 (버그가 발생한 환경을 적어주세요.):**

- 운영체제: windows 10
- 브라우저: chrome
- 버전: 109.0.5414.74(공식 빌드) (64비트)
- 스킨 버전 (스킨 버전은 index.xml 에서 확인): 3.6.5

**설명**
블로그를 접속하면 오늘 작성한 첫번째 글 우측에 이상한 링크가 보입니다.

**발생 과정**
블로그 접속하면 이미지 링크인 것 같은데 이미지가 안보이고 글자가 깨진형태로 나옵니다

**스크린샷 및 링크**
제이의 영리한 투자공부 - https://smartinvest.tistory.com

**Comment by KimJason8557** [comment]
스킨버전 3.6.3 이었네요. 
3.6.5 적용하면 무한로딩해버립니다.

**Comment by pronist** [comment]
@KimJason8557 무한로딩 관련해서는 기존의 이슈 참고 부탁드립니다. #167 #163 #157

**Comment by hyeonwook98** [comment]
저도 위에 분과 동일하게 이미지가 안보이고 글자가 깨진형태로 나오네요..
