### ISSUE TITLE
리스트 모드에서 포스트 설명 영역의 너비에 따라 섬네일 위치가 비 고정적으로 이동

### ISSUE THREAD

**Issue by julyrunt** [tistory-projects/tistory-skin-hELLO#170]
**환경 (버그가 발생한 환경을 적어주세요.):**

- 운영체제: windows
- 브라우저: chrome
- 버전: 109.0.5414.75
- 스킨 버전: 4.0.0

**설명**
리스트 모드에서 포스트 설명 영역의 너비에 따라 섬네일 위치가 비 고정적으로 이동하는 문제 발생

**발생 과정**
[data-mode=list] .post .description 에 flex-grow 값이 누락된 것으로 사료

**스크린샷 및 링크**
![screencapture-julyrunt-tistory-category-2023-01-22-00_22_12](https://user-images.githubusercontent.com/107601777/213873863-7e133abc-b9fe-432d-b7b6-d4dbdb9d9f55.png)

**Comment by pronist** [comment]
@julyrunt 버그가 확인되었습니다. 감사합니다.
