### ISSUE TITLE
댓글 입력을 못합니다.. (1월 27일 기준)

### ISSUE THREAD

**Issue by rockybear67** [tistory-projects/tistory-skin-hELLO#177]
**환경 (버그가 발생한 환경을 적어주세요.):**

- 운영체제: Windows 11
- 브라우저: Chromium 109
- 버전: 109
- 스킨 버전: 4.1.0

**설명**
버그가 어떻게 발생하는지 알려주세요. 대략적인 버그의 설명을 적어주시면 됩니다.

댓글을 입력하고 싶은데 티스토리 로그인이 되어 있음에도 계속 로그인하라는 메세지 창이 나타나면서 페이지가 새로고침만 됩니다. 댓글 창이 무너졌습니다.
만약 댓글창 입력이 된다면 브라우저 데이터를 삭제한 뒤, 재시도해보시기 바랍니다. 

**발생 과정**
버그가 어떤 과정을 통해 발생하는지 구체적으로 적어주세요.

상시로 발생되고 있습니다.

**스크린샷 및 링크**
![image](https://user-images.githubusercontent.com/7418669/215253764-2ee39cb2-ac76-47e1-9cf4-6f6050ab9160.png)

**Comment by pronist** [comment]
@rockybear67 티스토리 제약으로 2차 도메인에서는 댓글 입력을 할 수 없습니다. :)
