### ISSUE TITLE
today 조회수 카운팅이 되지 않습니다

### ISSUE THREAD

**Issue by hojunnnnn** [tistory-projects/tistory-skin-hELLO#184]
**환경 (버그가 발생한 환경을 적어주세요.):**

- 운영체제: windows
- 브라우저: chrome
- 버전:  109.0.5414.75
- 스킨 버전 4.1.0 / (이전 버전에서도 카운팅 비정상 작동)

**설명**
today 조회수 카운팅이 정상 작동하지 않습니다.
스킨 편집 혹은 게시글 등록,수정 등의 업데이트를 하면 갱신이 됩니다만, 그 외는 잘 안됩니다.(몇 시간 간격으로 갱신이 됨)
티스토리 문제일 수도 있을거 같아 티스토리 측에 문의 했었는데 스킨 치환자엔 문제 없다고 답변 받았습니다.

**발생 과정**
버그가 어떤 과정을 통해 발생하는지 구체적으로 적어주세요.
[e.g. 테마 변경 버튼을 통해 화이트 모드로 변경시 코드 하이라이팅의 색상이 변하지 않습니다. ...]

**스크린샷 및 링크**
블로그 주소 : https://dev-coco.tistory.com/
블로그 화면 조회수
![image](https://user-images.githubusercontent.com/59757689/216275239-1d437f13-ee31-4547-b6ce-012810384fb9.png)
블로그 관리 화면 조회수
![image](https://user-images.githubusercontent.com/59757689/216275372-3d0ce227-7595-4005-9a23-98a7f781ce28.png)

**Comment by pronist** [comment]
@hojunnnnn 안녕하세요.

아쉽게도 이 문제에 대해 제가 드릴 수 있는 답변은 없습니다. 저도 치환자를 단순하게 출력하고 있을 뿐, 스킨에서 별도로 연산하는 등 작업을 하고 있지는 않습니다.

https://github.com/tistory-projects/tistory-skin-hELLO/blob/44d9b9124e349781b63808f830c1dc589fcaf728/views/Sidebar/Counter.pug#L1-L13

따라서 이 문제에 대해 스킨 개발자의 입장에서 할 수 있는 일은 없습니다. 제 입장에서는 원인도 모르고, 해결 방법도 모를 뿐입니다. 당연히 수정을 할 수도 없습니다. 티스토리에서 주는 값을 그대로 출력하고 있는데 이것이 틀렸다면 스킨 개발자가 수정할 권리는 없는 것입니다.

**Comment by hojunnnnn** [comment]
@pronist 안녕하세요.

답변 감사합니다.
상우님은 저와 같이 조회수 관련 문제는 따로 없으신가요?

**Comment by pronist** [comment]
@hojunnnnn 개인적으로는 조회수 문제가 있었는지 그 문제의식조차 없었습니다. 방문자 수와 조회수를 신경쓰지 않다보니 조회수가 늦게 갱신되든 잘 통계가 안 잡히든 딱히 관심이 없습니다. 설령 문제가 있다고 해도 데이터를 블로그에 던지는 티스토리 통계 서버와 스킨에 통계를 출력 갱신하는 백엔드 측에 책임이 있는 것이니까요. 애초에 티스토리 통계는 그닥 믿을만한 구석이 되질 못해서 구글 애널리틱스를 씁니다.
