### ISSUE TITLE
페이지 내 이미지 사이즈 지정

### ISSUE THREAD

**Issue by gurcks8989** [tistory-projects/tistory-skin-hELLO#186]
**환경 (버그가 발생한 환경을 적어주세요.):**

- 운영체제: [macOS]
- 브라우저: [chrome]
- 스킨 버전 (스킨 버전은 index.xml 에서 확인): [4.1.0]

**설명**
버그가 어떻게 발생하는지 알려주세요. 대략적인 버그의 설명을 적어주시면 됩니다.

글쓰기 내부에서 지정한 이미지 사이즈가 먹통이네요. 
이미지 원본 크기로 출력되는 것 같은데, 그 이상의 사이즈는 1100px로 고정되서 나오는 것 같습니다.

그 전까지는 3.6.x 이하 버전을 쓰고 있을 때는 문제가 없었는데,
오늘 블로그 스킨 버전을 4.1.0으로 올리니깐 버그가 발생했습니다.

**스크린샷 및 링크**
버그가 발생한 상황을 가능하다면 스크린샷을 첨부해주세요. 또한 버그가 발생한 모습이 있는 포스트의 주소를 첨부해주시는 것도 아주 좋습니다!
![스크린샷 2023-02-03 오후 2 52 02](https://user-images.githubusercontent.com/23725576/216523201-21113ff2-9d17-41e2-a63e-307ef83dbd92.png)
![스크린샷 2023-02-03 오후 2 52 46](https://user-images.githubusercontent.com/23725576/216523317-c3290e10-0553-4dd6-b309-08d0b8547c5c.png)

**Comment by pronist** [comment]
@gurcks8989 안녕하세요.

이 부분은 버그로 확인되었습니다. 감사합니다.
