### ISSUE TITLE
'더보기' 가로줄이 좌측의 글씨 영역을 침범합니다

### ISSUE THREAD

**Issue by TetraTheta** [tistory-projects/tistory-skin-hELLO#189]
# 환경

- 운영체제: Windows 10 (19045.2546)
- 브라우저: Chrome v109.0.5414.120
- 스킨 버전: v4.1.0g

# 설명

![2023-02-04 22 37 33](https://user-images.githubusercontent.com/37061801/216770729-c6969ea8-75af-4eab-bc83-ea8d2df314d1.png)  

위 이미지처럼 가로 점선이 좌측의 '더보기' 글씨 영역을 침범하고 있습니다. 겹친 부분의 글씨를 읽기 힘듭니다.

# 발생 과정

글 작성 시 아래 코드처럼 `data-text-more`의 값을 '더보기'에서 변경합니다.
```html
<div data-ke-type="moreLess" data-text-more="소론파에 대해..." data-text-less="닫기"><a class="btn-toggle-moreless">더보기</a>
<div class="moreless-content">
</div>
</div>
```

# 추가 정보

`#content .contents_style [data-ke-type=moreLess]::before` 부분의 `width`가 `calc(100% - 90px)`으로 설정되어 있습니다. 이 부분을 조절하니 점선의 길이가 줄어듦을 확인할 수 있었습니다.  
해당 요소의 길이를 `data-text-more`의 내용에 따라 동적으로 조절할 수 있어야 할 것 같습니다.

**Comment by pronist** [comment]
@TetraTheta 감사합니다.  다음 배포 때 처리될겁니다.
