### ISSUE TITLE
스킨버전 ver4.1에서 사이드바 검색메뉴 text 입력 및 사용불가

### ISSUE THREAD

**Issue by theangkko** [tistory-projects/tistory-skin-hELLO#190]
**환경 (버그가 발생한 환경을 적어주세요.):**

- 운영체제: window11
- 브라우저: chrome / edge
- 버전: ver 109.0
- 스킨 버전 v4.1.0

**설명**
사이드바의 검색창에 글자 입력이 되지 않습니다. 
- 직접 입력도 되지 않고
- 복사해둔 글자를 복사-붙여넣기로 입력하려고 해도 되지 않습니다

**발생 과정**
간단히 테스트 해보니
- (제 브라우저 문제인지를 확인하기 위해) 기존 사용하던 ver 3.x로 되돌려서 테스트 해보니 정상적으로 검색가능한 상태임.
- (수정중이던 스킨으로 인해 문제 인지를 확인하기 위해) 수정 중이던 스킨이 아닌, 새롭게 스킨을 생성하여 ver 4.1 파일을 새로 등록하여 적용해도 검색메뉴 사용이 불가합니다.
- (동일스킨의 다른 블로그는 정상작동하는지 확인하기 위해)
  정상우님 블로그에서 검색해도 검색어가 입력되지를 않습니다.

**스크린샷 및 링크**

<img width="296" alt="image" src="https://user-images.githubusercontent.com/75212211/216783218-a4974dfd-5785-4d40-8095-777606f8fc26.png">

<img width="211" alt="image" src="https://user-images.githubusercontent.com/75212211/216783301-948db568-f69a-4da3-b694-931ac97d5bf8.png">

**Comment by pronist** [comment]
@theangkko 안녕하세요.

이 버그의 발생과정이 이해되지 않습니다. 제 환경에서는 제대로 입력과 검색이 되기 때문입니다. 마우스 커서로 입력하고, 검색은 엔터로 처리합니다.

![1](https://user-images.githubusercontent.com/25624965/216783586-a9660640-c9a3-496a-b1eb-65e0058d927a.png)
![2](https://user-images.githubusercontent.com/25624965/216783588-328bf250-fb1b-4c29-ad7d-f5ebadc23c67.png)

**Comment by theangkko** [comment]
![image](https://user-images.githubusercontent.com/75212211/216784186-751676a0-73e2-4b77-b672-89843e0751de.png)

아네!! 검색어가 들어가 있었는데, 색상이 같아서 안 보였던 겁니다.~!
