### ISSUE TITLE
코드 하이라이팅 이슈

### ISSUE THREAD

**Issue by che-ri** [tistory-projects/tistory-skin-hELLO#191]
**환경 (버그가 발생한 환경을 적어주세요.):**

- 운영체제: [e.g. windows]
- 브라우저: [e.g. chrome, safari]
- 버전: [e.g. 22]
- 스킨 버전 (스킨 버전은 index.xml 에서 확인): [e.g 3.4.0]

**설명**
버그가 어떻게 발생하는지 알려주세요. 대략적인 버그의 설명을 적어주시면 됩니다.
[e.g. 코드 하이라이팅이 동작하지 않습니다.]

티스토리에서 제공하는 코드 하이라이팅 제거를 했음에도 불구하고, 코드 하이라이팅이 제대로 동작하지 않는 듯 하여 남깁니다.

**발생 과정**
버그가 어떤 과정을 통해 발생하는지 구체적으로 적어주세요.
[e.g. 테마 변경 버튼을 통해 화이트 모드로 변경시 코드 하이라이팅의 색상이 변하지 않습니다. ...]

화이트모드, 다크모드 둘다 코드 하이라이팅이 적용되지 않는 것 같습니다!
혹 현재 버전에서 코드 하이라이팅이 빠졌나요?

**스크린샷 및 링크**
버그가 발생한 상황을 가능하다면 스크린샷을 첨부해주세요. 또한 버그가 발생한 모습이 있는 포스트의 주소를 첨부해주시는 것도 아주 좋습니다!

스킨 적용 후 코드 부분이 아래와 같이 적용됩니다.
![스크린샷](https://user-images.githubusercontent.com/76051880/216858207-b3edf9d1-a199-4707-a30f-72953c1bbdc1.png)

**Comment by pronist** [comment]
@che-ri 안녕하세요. 증상이 발생한 블로그의 포스트 주소를 적어주시면 감사하겠습니다.

**Comment by che-ri** [comment]
스킨 적용 방식을 스킨 편집이 아닌 스킨 등록을 사용하여 적용하니 정상 작동됩니다! 혹 h1와 blockquote은 다크모드 지원이 되지 않는 걸까요? 그 부분만 검정색으로 나와서요!

**Comment by pronist** [comment]
@che-ri 

혹시, 마크다운 모드 또는 복사 & 붙여넣기로 작성하고 계신가요? 이 스킨은 마크다운은 지원하지 않습니다. `h1` 같은 경우에는 포스트의 제목도 `h1` 으로 처리하고 있어서 이를 본문에 쓰게되면 일단은 SEO 에서 지적을 당하게 되니까 제외하였고, `blockquote` 의 경우에도 티스토리 기본 에디터로 작성한 것 이외에는 스타일이 적용되지 않습니다.  티스토리 기본 에디터로 작성된 인용문구는 `data-ke-type` 이라는 속성을 가지고 있기 때문에 그것만 처리된답니다.

**Comment by che-ri** [comment]
@pronist 아뇨~ 마크다운으로 작성하고 있지 않습니다~ 새로적은 글은 [테스팅 링크](https://cheri.tistory.com/299) 잘 작성되어지는데, 이전에 작성한 글에는 적용이 안되네요 😂

**Comment by pronist** [comment]
@che-ri 

그렇군요. 일단, 사용하고 계신 스킨을 살펴보니 v3. x 인 것 같습니다. 현 버전은 v4.1 입니다.

명확한 해답은 아니지만, 티스토리 에디터가 생각보다 잠수함 패치를 많이 합니다. 없던 속성이 생기고 있던 속성이 사라지고 그런 경우가 종종 있습니다. 에디터에서 작성되는 최신을 기준으로 따라가려고 가급적 노력하기는 하는데, 과거의 글과 새로 작성된 글의 차이가 다소 있는 경우(있던 속성이 사라졌다든가)에는 호환이 되지 않을 수도 있습니다. 티스토리 기본 스킨의 경우에는 최대한 호환성을 유지하려고 하다 보니 본문의 디자인은 크게 신경을 쓰지 않은 것 같더군요.

아무래도 블로거가 글에 어떤 요소를 넣을지 짐작이 안 되다 보니 섣불리 일반화를 해서 스타일을 지정할 수가 없는데, 티스토리 스킨 에디터가 패치될 수록 일반화보다는 딱 선택자를 지정해서 넣기 수월하게 되어있습니다. 스킨의 패치도 그런 방향으로 되다보니 과거의 글하고 호환성이 떨어질 수는 있겠다는 생각이 듭니다. :(
