### ISSUE TITLE
다운로드 버튼에서 글씨가 일부 잘리는 현상

### ISSUE THREAD

**Issue by TetraTheta** [tistory-projects/tistory-skin-hELLO#192]
# 환경

- 운영체제: Windows 10 (19045.2546)
- 브라우저: Chrome v109.0.5414.120
- 스킨 버전: v4.1.1a

# 설명

![2023-02-06 16 18 01](https://user-images.githubusercontent.com/37061801/216908264-57c27393-4c63-4ad2-a130-de9fbd618832.png)

위 이미지처럼 다운로드 버튼의 글씨가 일부 잘려서 출력됩니다.

# 발생 과정

글 작성 시 파일을 첨부합니다.

# 추가 정보

![2023-02-06 16 18 19](https://user-images.githubusercontent.com/37061801/216908360-90ec7559-7a86-4ebd-bcd0-a6019875c7e1.png)

`figure.fileblock .name, #tt-body-page figure.fileblock .name`의 `overflow: hidden` 규칙을 비활성화 하자 위와 같이 정상적으로 글씨가 출력됨을 확인했습니다. `display: block`을 비활성화 해도 글씨가 정상적으로 출력됩니다.

**Comment by pronist** [comment]
@TetraTheta 안녕하세요.

크리티컬한 버그는 아닌 것 같아서 추후 패치 때 한꺼번에 처리해보도록 하겠습니다.
