### ISSUE TITLE
목차가 일정 수준을 넘어갔을 때 스크롤되지 않는 문제

### ISSUE THREAD

**Issue by mmcrs** [tistory-projects/tistory-skin-hELLO#200]
# **사용환경**

**데스크톱 환경**
- 운영체제: Windows 11 (22623.1325)
- 브라우저: Firefox Beta 111.0b4, Edge 110.0.1587.50

**모바일 환경**
- 운영체제: Android 13
- 브라우저: Firefox Beta 111.0b4, Chrome 110.0.5481.65

**스킨**
- 스킨 버전: 4.1.2

# **발생 과정과 스크린샷**

![ddddd](https://user-images.githubusercontent.com/85152618/220825624-f804ec9d-3903-42b9-ac2f-189f445bd73c.png)

[해당 글](https://mmcrs.in/400)을 예로 들면 목차가 많은데 이로 인해 화면에서 벗어나고 아래로 스크롤 하여 내려볼 수 있어야 하는데 스크롤이 불가능합니다.

**Comment by pronist** [comment]
@mmcrs 안녕하세요.

버그라고 본다면 그럴 수 있지만, 목차를 많이 정의하는 것은 일반적으로 드문 경우이기 때문에 반영이 안 될 수도 있습니다.

**Comment by pronist** [comment]
@mmcrs 검토해보니 나쁘지 않을 것 같아서 반영했습니다 ~
