### ISSUE TITLE
이미지가 글에 안올라가는 버그발견

### ISSUE THREAD

**Issue by dongwook98** [tistory-projects/tistory-skin-hELLO#204]
**환경 (버그가 발생한 환경을 적어주세요.):**

- 운영체제: macOS
- 브라우저: chrome
- 버전: hELLO 4.1.2
- 스킨 버전 (스킨 버전은 index.xml 에서 확인): hELLO 4.1.2

**설명**
글쓰기에서 이미지를 올렸는데 글에는 안올라가요!!

**발생 과정**
글쓰기에서 이미지를 올렸는데 글에는 안올라가요!!

**스크린샷 및 링크**
버그가 발생한 상황을 가능하다면 스크린샷을 첨부해주세요. 또한 버그가 발생한 모습이 있는 포스트의 주소를 첨부해주시는 것도 아주 좋습니다!
![image](https://user-images.githubusercontent.com/119502777/221451562-d9ee863b-6948-4286-8726-37b36e22f3f2.png)

![image](https://user-images.githubusercontent.com/119502777/221451578-bcea889d-3ca8-4e67-aa31-df57f9c79316.png)

https://dongwookit.tistory.com/161

**Comment by dongwook98** [comment]
https://dongwookit.tistory.com/manage/design/skin/edit#/

**Comment by dongwook98** [comment]
가운데 정렬하니 잘보입니다.. 왼쪽 정렬이 안되네요!!

**Comment by pronist** [comment]
@dongwook98 안녕하세요.

확인해보니 이것은 명백한 버그로 판명되었습니다. 제보해주셔서 감사합니다.

**Comment by pronist** [comment]
@dongwook98 반영이 완료되었습니다~

**Comment by dongwook98** [comment]
감사합니다!
