### ISSUE TITLE
포스팅에 Github Gist embed 추가 시 나타나지 않는 현상

### ISSUE THREAD

**Issue by juyoungIt** [tistory-projects/tistory-skin-hELLO#205]
**환경**
- 운영체제: Mac OS Ventura 13.2.1(22D68)
- 브라우저: chrome
- 버전: hELLO 4.1.3
- 스킨 버전: 4.1.3
**설명**
Github Gist에서 얻은 embed 링크를 첨부하였는 데 나타나지 않는 현상입니다.
(검사를 통해 확인해본 결과, 해당 구분은 html 문서상에 삽입되어 있습니다.)

**발생 과정**
포스팅을 작성하면서 Github Gist로 작성한 코드를 html 모드로 embed 링크를 첨부하였는 데 포스팅에서 나타나지 않는 현상이 나타났습니다.

**스크린샷 및 링크**
(4. 글을 마치면서 윗 부분에 gist embed 링크를 삽입하였습니다.)
https://juyoungit.tistory.com/660

**Comment by pronist** [comment]
안녕하세요. #185 참고 부탁드립니다 :)

**Comment by juyoungIt** [comment]
안녕하세요! 이미 등록 되었던 이슈인데 제가 번거로움을 드렸네요. 죄송합니다.
그런 기술적인 부분과 관련된 현상일 줄은 몰랐네요. 친절히 확인해주셔서 정말 감사합니다!

**Comment by pronist** [comment]
@juyoungIt 저도 이 부분은 해결하고 싶은 마음이 굴뚝같지만, 현재 두 마리의 토끼를 잡는 것을 기술적으로 지원하지 않는 상황입니다. 내부적으로 `<template>` 를 사용하는데, 현재 `<template>` 내부에서 `<script src="..."></script>` 를 사용하는 경우 네트워크의 요청은 이루어지는 것으로 판명되었으나 `Gist` 스크립트에서 처리하는 `document.write` 는 처리되지 않습니다. 이 문제는 제 스킨에서만 발생하는 문제이므로 다른 스킨에서는 정상처리 될거에요. :D

**Comment by juyoungIt** [comment]
@pronist 네! 친절하게 안내해주셔서 감사합니다. 좋은 템플릿을 무료로 배포해주셔서 감사히 잘 사용하고 있습니다 ㅎㅎ 정말 감사합니다!
