### ISSUE TITLE
구독 버튼을 눌러도 구독이 되지 않습니다

### ISSUE THREAD

**Issue by HiBixby** [tistory-projects/tistory-skin-hELLO#206]
**환경 (버그가 발생한 환경을 적어주세요.):**

- 운영체제: windows11
- 브라우저: edge, whale
- 버전:  엣지 버전 110.0.1587.69 (공식 빌드) (64비트) / 웨일 버전 3.19.166.16(공식 빌드) (64비트) 
- 스킨 버전 (스킨 버전은 index.xml 에서 확인): 4.1.3

**설명**
버그가 어떻게 발생하는지 알려주세요. 대략적인 버그의 설명을 적어주시면 됩니다.
구독 버튼(별모양 버튼)이 동작하지 않는 것 같습니다.
구독 버튼의 css hover 효과는 동작합니다. 하지만 눌러도 아무런 반응이 없고 구독도 되지 않습니다.

**발생 과정**
버그가 어떤 과정을 통해 발생하는지 구체적으로 적어주세요.
글 공유하기 버튼 라인에 있는 별 아이콘 구독버튼과 블로그 우측 상단의 별 아이콘 구독버튼을 눌러도 반응이 없습니다.
https://www.tistory.com/feed/following 에 들어가도 구독중인 블로그에 뜨지 않습니다.
제 블로그 뿐만 아니라 이 스킨 개발자 분의 티스토리 블로그에서 별 아이콘 버튼을 눌러도 구독이 되지 않아서 이곳에 글을 올리게 되었습니다.
아무런 확장 프로그램이 깔리지 않은 순수 edge 브라우저에서 시도해봐도 구독이 되지 않습니다.

**스크린샷 및 링크**
버그가 발생한 상황을 가능하다면 스크린샷을 첨부해주세요. 또한 버그가 발생한 모습이 있는 포스트의 주소를 첨부해주시는 것도 아주 좋습니다!

**Comment by pronist** [comment]
**구독 버튼과 댓글에 관하여**

제 스킨이 아닌 티스토리의 제약사항입니다.

1. 2차 도메인에서는 구독과 댓글을 쓸 수 없습니다.
2. 자신의 블로그는 구독을 할 수 없습니다.
3. 로그인이 되어있는 상태가 아니면 구독이 되지 않습니다.
4. 2차 도메인에서는 HTTPS 제약으로 로그인과 관련된 활동이 안됩니다.

블로그의 링크를 안 남겨주셨기 때문에 제가 직접 테스트하지 못하므로 구독 버튼으로 발생할 수 있는 경우에 대해 설명해드렸습니다. 댓글과 구독 버튼에 대한 내용은 또 다른 이슈와 디스커션, 블로그 댓글에서도 찾아보실 수 있으니 참고 부탁드립니다. 이는 이미 수차례 보고된 이슈이므로 닫겠습니다. 여담으로, 제 블로그는 2차 도메인이 적용되어 있으므로 구독처리가 되지않습니다.

**Comment by HiBixby** [comment]
개발자님의 2차도메인을 사용하지 않은 주소인 https://pronist.tistory.com/5 에서도 동일한 현상이 발생되어 스킨의 문제라고 생각했었네요!
해당 스킨을 사용한 다른 블로그들에서는 구독 처리가 되는 것을 확인하였습니다.
하지만 구독 버튼이 작동하더라도, 버튼을 눌렀을 때 아무런 인터렉션이 발생하지 않아 버튼이 동작했는지 확인하기 어려웠습니다.
해당 부분을 새 기능으로 고려해주시면 감사하겠습니다.

**Comment by ten-log** [comment]
윗분과 같은 이유로 여유있으실때 업데이트가 되면 더욱 좋을듯합니다 응원합니다!
