### ISSUE TITLE
이미지가 잘 적용되지않습니다

### ISSUE THREAD

**Issue by luxis-luxis** [tistory-projects/tistory-skin-hELLO#207]
**환경 (버그가 발생한 환경을 적어주세요.):**

- 운영체제: [e.g. windows]
- 브라우저: [e.g. chrome]
- 버전: [e.g. 22]
- 스킨 버전 (스킨 버전은 index.xml 에서 확인): [e.g 3.4.0]

**설명**
대표 이미지가 잘 적용되지않습니다.
**발생 과정**
버그가 어떤 과정을 통해 발생하는지 구체적으로 적어주세요.
[e.g. 대표이미지가 적용되지않습니다]

**스크린샷 및 링크**
https://insightclip.tistory.com/

**Comment by pronist** [comment]
@luxis-luxis 구 버전을 사용하고 계신 것 같습니다. 제 블로그에서 신버전을 다운받아서 사용해주세요. 버전이 명시되어 있지 않으면 파악하기 어려운 점 양해부탁드립니다.
