### ISSUE TITLE
그리드/갤러리 사용 시 세로 한 줄로 표시됨

### ISSUE THREAD

**Issue by TetraTheta** [tistory-projects/tistory-skin-hELLO#60]
## 환경
- 운영체제: Windows 11 build 22000.556
- 브라우저: Firefox 98.0.2
- 스킨 버전: 3.6.1

## 설명
커버 기능에서 커버 아이템 표시유형을 '그리드' 혹은 '갤러리'를 사용 시 항목들이 세로 한 줄로만 표시됨

세로 한 줄로만 표시되는 것이 아닌, 가로로 3~4개의 항목을 표시한 후 다음 줄로 넘어가야 함

## 발생 과정
'커버 아이템'을 '그리드' 혹은 '갤러리'로 설정 후, 설정을 저장하고 좌측의 미리보기 화면이나 실제 블로그 화면을 새로고침

## 스크린샷 및 링크
![이미지 1](https://user-images.githubusercontent.com/37061801/160269836-ee367262-2aa8-4a58-b872-4f92da651c8b.png)

<https://tetralog.tistory.com> (임시로 홈 화면을 문제가 발생하는 커버 아이템들로 설정해두었습니다)

## 기타
예전 버전부터 있었던 버그 같습니다. 티스토리 스킨 저장 기능을 통해 저장해둔 스킨 버전이 3.5.1로 메모가 되어 있던데, 그 스킨을 사용했을 때에도 똑같은 일이 발생해 최신 버전으로 업데이트를 했으나, 여전히 해당 버그가 발생해 버그 리포트를 남깁니다.

다른 커버 아이템 표시 유형에서는 별다른 버그를 현재까지는 발견하지 못했습니다.

AdGuard와 Privacy Badger의 사용이 해제된 상태에서 작성되었으므로, 해당 애드온이 문제를 일으켰을 가능성은 적은 것으로 보입니다.  
AdGuard는 브라우저 확장 프로그램에서 '이 웹사이트에서 활성화됨'이 토글 오프 되어 있으며, Privacy Badger 역시 'Disable for this site'가 선택된 상황입니다.

**Comment by pronist** [comment]
@TetraTheta 이것은 처음보는 버그군요. 어떤 상황에서 발생하는지 원인을 알 수 없어서 다소 아쉬운 부분은 있습니다. 제 블로그에도 동일한 증상이 있었다면 바로 처리되었을 텐데 트리거가 되는 부분을 모르겠네요. 우선 인지는 하고있도록 하겠습니다. 다만 처리에 있어서는 다소 늦어질 예정입니다.

**Comment by TetraTheta** [comment]
현재 의심되는 부분은 '컨텐츠 너비'인데, 이에 대한 실험을 하지 않아 정확히 이것이 문제의 원인인지 알 수 없습니다.

위 사이트는 '컨텐츠 너비'의 모든 항목('홈/글 목록', '글', '방명록', '태그 클라우드')의 너비를 `1100`으로 설정했습니다. '글', '방명록'이 `720`으로 기본 설정되어 있는 부분과 차이가 있습니다.

그 이외에는 연관이 될 만한 것이 별로 없는 상태입니다. 기껏해야 글 작성자를 표시하지 않고, 카테고리의 모든 항목을 표시하도록 한 것이 전부인지라...

**Comment by pronist** [comment]
@TetraTheta 제 블로그에서도 그리드 커버아이템을 이리저리 왔다갔다 시켜보니 동일한 증상이 있는 것을 파악했습니다. 뭔가 다른 커버 아이템이랑 함께 사용할 때 단독으로 사용하더라도 그리드가 제일 위에 위치하면 버그가 발생하는군요. 아무래도 그리드의 위치에 따라 문제를 일으키는 듯 싶네요. 갤러리도 그리드랑 같은 원리로 동작하는거라 마찬가지일 것이구요. 이에 대한 정확한 원인은 모르겠지만 트리거는 대강 알게되었으니 이슈를 처리할 때 참고가 될 것습니다. 버그신고 감사드립니다.

**Comment by pronist** [comment]
@TetraTheta 4.0.0 에서 처리완료!
